project_name: project
report_sizes: true

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/google/wire/cmd/wire@latest
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
    - go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .
    - go test -race ./...

builds:
  -
    id: default
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, windows, darwin ]
    goarch: [ amd64, arm64 ]
#    skip: true # useful for library projects

upx:
  -
    ids: [ default ]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [ linux, windows ] # skip darwin (macOS 13.x Ventura is not supported now)
    goarch: [ amd64, arm64 ]

release:
  ids: [ default ]
  draft: true
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  #  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Install or update
    
    For native Go installation (any platforms):
    
    ```console
    go install github.com/koddr/project@latest
    ```

    For [Homebrew][brew_url] users (GNU/Linux, macOS):
    
    ```console
    # Tap a new formula:
    brew tap koddr/tap
    
    # Installation:
    brew install koddr/tap/project
    
    # Upgrade to the latest:
    brew upgrade koddr/tap/project
    ```
    
    > 💡 Note: See the [`Wiki page`][wiki_url] to understand structures of JSON files and get general recommendations.
    
    ## Your help to improve project
    
    I'd be truly grateful for help with:
    
    - Creating tests (and/or benchmarks) for code
    - Improving existing functions, structs, or tests
    - Feature requests with interesting functions that would be good to add
    
    Your PRs & issues are welcome! Thanks 😉
    
    [brew_url]: https://brew.sh
    [wiki_url]: https://github.com/koddr/project/wiki
  disable: false
  skip_upload: false

dockers:
  -
    id: '{{ .ProjectName }}'
    ids: [ default ]
    image_templates:
      - 'koddr/{{ .ProjectName }}:latest'
      - 'koddr/{{ .ProjectName }}:{{ .Tag }}'
      - 'koddr/{{ .ProjectName }}:v{{ .Major }}'
      - 'koddr/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=linux/amd64'
    skip_push: false
    push_flags:
      - '--tls-verify=false'

brews:
  -
    repository:
      owner: koddr
      name: homebrew-tap
      branch: main
      token: '{{ .Env.GITHUB_TOKEN }}'
      pull_request:
        enabled: true
      git:
        url: 'git@github.com:koddr/homebrew-tap.git'
        private_key: '{{ .Env.BREW_PRIVATE_KEY_PATH }}' # don't forget to create this before release!
    commit_author:
      name: Vic Shóstak
      email: koddr.me@gmail.com
    commit_msg_template: 'Brew formula update for {{ .ProjectName }} version {{ .Tag }}'
    folder: Formula
    caveats: |
      How to use this project.
    homepage: 'https://github.com/koddr/{{ .ProjectName }}'
    description: |
      Description of my project.
    license: Apache 2.0
    skip_upload: false
#    dependencies:
#      - name: git

nix:
  -
    name: '{{ .ProjectName }}'
    commit_author:
      name: Vic Shóstak
      email: koddr.me@gmail.com
    commit_msg_template: 'Nix package update for {{ .ProjectName }} version {{ .Tag }}'
    homepage: 'https://github.com/koddr/{{ .ProjectName }}'
    description: |
      Description of my project.
    license: Apache 2.0
    skip_upload: false
    repository:
      owner: koddr
      name: 'nixpkg-{{ .ProjectName }}'
      branch: main
      token: '{{ .Env.GITHUB_TOKEN }}'
      pull_request:
        enabled: true
      git:
        url: 'git@github.com:koddr/nixpkg-{{ .ProjectName }}.git'
        private_key: '{{ .Env.NIX_PRIVATE_KEY_PATH }}' # don't forget to create this before release!

nfpms:
  -
    maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      Description of my project.
    homepage: 'https://github.com/koddr/{{ .ProjectName }}'
    license: Apache 2.0
    formats: [ deb, rpm, apk, archlinux ]
#    dependencies: [ git ]

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE, README.md ]

checksum:
  name_template: 'checksums.txt'

changelog:
#  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude: [ '^*.md', '^*.ya?ml' ]
  groups:
    - title: Features
      regexp: ^.*?(F|f)eature.*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
