name: Linter

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    strategy:
      matrix:
        go: [ stable ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Download Go dependencies
        run: go download
      - name: Install go-critic linter
        run: go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      - name: Run go-critic linter
        run: gocritic check -enableAll ./...
