name: Golang workflow

on:
  push:
    paths: [ '**.go' ]
  pull_request:
    paths: [ '**.go' ]

jobs:
  build:
    strategy:
      matrix:
        go: [ 'stable' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run "google/wire" for dependency injection
        run: go run github.com/google/wire/cmd/wire@latest

      - name: Run "govulncheck" for scanning code for known vulnerabilities in dependencies
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...

      - name: Run "google/osv-scanner" to identify vulnerabilities in dependencies
        run: go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .

      - name: Run "securego/gosec" for security checks
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...

      - name: Run "go-critic/go-critic" for code linting
        run: go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...

      - name: Run Go test with coverage report
        run: go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
